version: '2'

services:

  issue-bot:
    container_name: issue-bot
    build: .
    ports:
      - "8080:80"
    volumes:
      - /data
    environment:
      - NODE_ENV=docker
      - GITHUB_TOKEN=e7e0a931acf36746269b229424ba769f409a8d16
      - GITHUB_CLIENT_ID=33beb04a03e6bdee1049
      - GITHUB_CLIENT_SECRET=a9d801431462dd5c7aef4c62548975da4d3fcac5
      - DB_DATABASE=issuebot
      - DB_USERNAME=issuebot
      - DB_PASSWORD=issuebot
      - DB_HOST=database
      - DB_DIALECT=postgres

  database:
    container_name: issue-bot-database
    image: postgres:alpine
    ports:
      - "5432:5432"
    volumes:
      - /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=issuebot
      - POSTGRES_USER=issuebot
      - POSTGRES_PASSWORD=issuebot